later(function()
    add("ibhagwan/fzf-lua")
    require("fzf-lua").setup()

    keymap("n", "<leader>,", "<cmd>FzfLua buffers sort_mru=true sort_lastused=true<cr>", { desc = "Switch Buffer" })
    keymap("n", "<leader>:", "<cmd>FzfLua command_history<cr>", { desc = "Command History" })

    keymap("n", "<leader>sa", "<cmd>FzfLua autocmds<cr>", { desc = "Auto Commands" })
    keymap("n", "<leader>sb", "<cmd>FzfLua buffers sort_mru=true sort_lastused=true<cr>", { desc = "Buffers" })
    keymap("n", "<leader>sd", "<cmd>FzfLua diagnostics_document<cr>", { desc = "Document Diagnostics" })
    keymap("n", "<leader>sD", "<cmd>FzfLua diagnostics_workspace<cr>", { desc = "Workspace Diagnostics" })
    keymap("n", "<leader>sf", "<cmd>FzfLua files<cr>", { desc = "Files" })
    keymap("n", "<leader>sg", "<cmd>FzfLua grep_visual<cr>", { desc = "Grep" })
    keymap("n", "<leader>sh", "<cmd>FzfLua help_tags<cr>", { desc = "Help Pages" })
    keymap("n", "<leader>sH", "<cmd>FzfLua highlights<cr>", { desc = "Search Highlight Groups" })
    keymap("n", "<leader>sj", "<cmd>FzfLua jumps<cr>", { desc = "Jumplist" })
    keymap("n", "<leader>sk", "<cmd>FzfLua keymaps<cr>", { desc = "Key Maps" })
    keymap("n", "<leader>sM", "<cmd>FzfLua man_pages<cr>", { desc = "Man Pages" })
    keymap("n", "<leader>sr", "<cmd>FzfLua oldfiles<cr>", { desc = "Recent" })
    keymap("n", "<leader>sR", "<cmd>FzfLua resume<cr>", { desc = "Resume" })
    keymap("n", "<leader>sq", "<cmd>FzfLua quickfix<cr>", { desc = "Quickfix List" })
end)
